// Turns dist/index.html (one self-contained file) into src/channels/voice-mode-page.ts,
// the module the adapter serves. Never edit the generated module by hand.
import { readFileSync, writeFileSync } from "node:fs"
import { createHash } from "node:crypto"
import { execFileSync } from "node:child_process"
import { fileURLToPath } from "node:url"
import path from "node:path"

const here = path.dirname(fileURLToPath(import.meta.url))
const html = readFileSync(path.join(here, "..", "dist", "index.html"), "utf8")
const out = path.join(here, "..", "..", "..", "..", "..", "src", "channels", "voice-mode-page.ts")

const kb = Math.round(html.length / 1024)

// An explicit build-input list ignores editor files and local notes. The source
// and generated page live on the same registry branch and are checked together.
const uiRoot = path.join(here, "..")
const inputs = JSON.parse(readFileSync(path.join(uiRoot, "source-files.json"), "utf8"))
const hash = createHash("sha256")
for (const rel of ["source-files.json", ...inputs].sort()) {
  hash.update(rel + "\0")
  hash.update(readFileSync(path.join(uiRoot, rel)))
  hash.update("\0")
}
const sourceHash = hash.digest("hex")
const body = `/* eslint-disable */
/**
 * GENERATED by .claude/skills/add-voice-mode/ui (pnpm build) — do not edit by hand.
 *
 * The browser call page for the voice channel as one self-contained HTML
 * document (${kb} KB).
 */

/** sha256 over the ui/ sources this module was generated from; the channel tests check it. */
export const UI_SOURCE_HASH = '${sourceHash}';

const PAGE = ${JSON.stringify(html)};

/** The call page. */
export function callPageHtml(): string {
  return PAGE;
}
`
writeFileSync(out, body)
// Match the repository's prettier so the pre-commit hook has nothing to rewrite.
try {
  const prettier = path.join(here, "..", "..", "..", "..", "..", "node_modules", ".bin", "prettier")
  execFileSync(prettier, ["--write", out], { stdio: "ignore" })
} catch {
  /* prettier not installed at the repository root; the hook will format it on commit */
}
console.log(`wrote ${path.relative(process.cwd(), out)} (${kb} KB of HTML)`)
