// Turns dist/index.html (one self-contained file) into src/channels/gpt-live-call-page.ts,
// the module the adapter serves. The page keeps a placeholder comment where the host injects
// its runtime config; callPageHtml() fills it. Never edit the generated module by hand.
import { readFileSync, writeFileSync } from "node:fs"
import { createHash } from "node:crypto"
import { execFileSync } from "node:child_process"
import { fileURLToPath } from "node:url"
import path from "node:path"

const here = path.dirname(fileURLToPath(import.meta.url))
const html = readFileSync(path.join(here, "..", "dist", "index.html"), "utf8")
if (!html.includes("<!--VOICE_UI_CONFIG-->")) throw new Error("dist/index.html lost the VOICE_UI_CONFIG placeholder")
const out = path.join(here, "..", "..", "..", "..", "..", "src", "channels", "gpt-live-call-page.ts")

const kb = Math.round(html.length / 1024)

// An explicit build-input list ignores editor files and local notes. The source
// and generated page live on the same registry branch and are checked together.
const uiRoot = path.join(here, "..")
const inputs = JSON.parse(readFileSync(path.join(uiRoot, "source-files.json"), "utf8"))
const hash = createHash("sha256")
for (const rel of ["source-files.json", ...inputs].sort()) {
  hash.update(rel + "\0")
  hash.update(readFileSync(path.join(uiRoot, rel)))
  hash.update("\0")
}
const sourceHash = hash.digest("hex")
const body = `/* eslint-disable */
/**
 * GENERATED by .claude/skills/add-voice/ui (pnpm build) — do not edit by hand.
 *
 * The browser call page for the Live Voice channel as one self-contained HTML
 * document (${kb} KB). The host injects a small runtime config where the
 * VOICE_UI_CONFIG placeholder sits, so operators can change the look without
 * rebuilding: see VoiceUiConfig and the GPT_LIVE_UI key in SKILL.md.
 */

export interface VoiceUiConfig {
  /** Visual language: the Teenage Engineering inspired device (default) or the NanoClaw card. */
  skin?: 'te' | 'nanoclaw';
  /** Device finish for the te skin; auto follows the viewer's light/dark setting. */
  colorway?: 'auto' | 'ivory' | 'field' | 'rabbit';
  /** Screen beside a control rail (default) or everything stacked. */
  layout?: 'rail' | 'stack';
  /** What shows the voice: the dot matrix (default) or bars. */
  presence?: 'matrix' | 'bars';
  /** Product name in the header. */
  brand?: string;
  /** Footer line; {agent} is replaced with the wired agent's name. */
  footer?: string;
  /** Print keyboard shortcuts on the keys (desktop only). */
  shortcuts?: boolean;
  /** Show a timestamp on each transcript turn. */
  timestamps?: boolean;
  /** Let the caller pick a colorway from the page (remembered in their browser). */
  colorwayPicker?: boolean;
}

/** sha256 over the ui/ sources this module was generated from; the channel tests check it. */
export const UI_SOURCE_HASH = '${sourceHash}';

const PAGE = ${JSON.stringify(html)};

function safeJson(value: unknown): string {
  // Inline <script> content must never contain a closing tag or U+2028/2029.
  return JSON.stringify(value)
    .replace(/</g, '\\\\u003c')
    .replace(/\\u2028/g, '\\\\u2028')
    .replace(/\\u2029/g, '\\\\u2029');
}

/** The call page with the host's runtime config injected. */
export function callPageHtml(config: VoiceUiConfig = {}): string {
  // A function replacer: a string replacement would interpret $& and $' inside the config.
  return PAGE.replace('<!--VOICE_UI_CONFIG-->', () => '<script>window.__VOICE_UI__=' + safeJson(config) + '</script>');
}
`
writeFileSync(out, body)
// Match the repository's prettier so the pre-commit hook has nothing to rewrite.
try {
  const prettier = path.join(here, "..", "..", "..", "..", "..", "node_modules", ".bin", "prettier")
  execFileSync(prettier, ["--write", out], { stdio: "ignore" })
} catch {
  /* prettier not installed at the repository root; the hook will format it on commit */
}
console.log(`wrote ${path.relative(process.cwd(), out)} (${kb} KB of HTML)`)
